package com.gyenno.ruiyun.datamigration.model.util;

import lombok.Data;

@Data
public class TableId {
    private int PatientInfoId;
    private int PatientCaseId;
    private int PatientScaleId;
    private int PatientOptionId;
    private int PatientDiseaseOrderId;
    private int PatientMedhistoryId;
    private int PatientHabitId;
    private int PatientHistoryId;
    private int PatientFirstSymbolId;
    private int PatientDiseaseId;
    private int PatientAllergyId;
    private int PatientFamilyHistoryId;
    private int PatientCideexposedHistoryId;
    private int PatientDependentsId;
    private int PatientAccompanyingDiagnosisId;
    private int PatientPaperoptionId;
    private int PatientDiaryId;
    private int PatientDiseaseComplicationId;
    private int PatientSymptomId;
    private int PatientMedicineId;
    private int PatientMedicineDetailId;
    private int PatientCombineMedicineId;
    private int PatientCombineMedicineDetailId;
    private int PatientVideoInfoId;
    private int PatientAttachmentId;
    private int PatientGaitId;
    private int PatientGaitItemId;
    private int PatientGaitCheckId;
    private int PatientElecTroGramId;
    private int PatientMotNerCondResuId;
    private int PatientFWavStuResuId;
    private int PatientSenNerCondResuId;
    private int PatientNeedExamResuId;
    private int PatientMotUniAnaResuId;
    private int PatientIntPatAnaItemId;
    private int PatientFieldDetailId;
    private int PatientNerveSleepId;
    private int PatientInspectId;
    private int PatientBioexamId;
    private int PatientBioexamResultId;
    private int PatientGeneMutationInfoId;
    private int PatientBodypartId;
    private int PatientVitalSignId;
    private int PatientVitalSignDetailId;
    private int PatientPhytheReactionId;
    private int PatientPhytheTmsId;
    private int PatientPhytheAssessId;
    private int PatientAdverseId;
    private int PatientPreopsInfoId;
    private int PatientPreopsDiaryId;
    private int PatientPreopsScaleId;
    private int PatientPreopsMedicineId;
    private int PatientTreatmentId;
    private int PatientComplicationId;
    private int PatientDbsFirstId;
    private int PatientDbsFollowId;
    private int PatientDbsFirstDetailId;
    private int PatientDbsMedicineId;
    private int PatientDbsChooseId;
    private int PatientDbsParameterId;
    private int PatientScaleFileId;
    private int PatientAdverseMedicineId;
    private int PatientAdverseSeriousId;
    private int PatientFirstVisitTreatmentId;
    private int PatientExerciseId;
    private int PatientMedicineAdverseId;
    private int PatientMedicineAdverseMdId;
    private int PatientSpephysicalId;
}
